In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv("CAFE_SALES_CLEANED(in).csv")
df.head(20)

,TXN,Transaction number,Item,Quantity_Avg,Price_per_unit_Avg,Total_spent_Avg,Payment Method,Location,Transaction Date
0,TXN,1961373,Coffee,2.0,2.0,4.000000,Credit Card,Takeaway,9/8/2023
1,TXN,4977031,Cake,4.0,3.0,12.000000,Cash,In-store,5/16/2023
2,TXN,4271903,Cookie,4.0,1.0,8.924352,Credit Card,In-store,7/19/2023
3,TXN,7034554,Salad,2.0,5.0,10.000000,Unknown,Unknown,4/27/2023
4,TXN,3160411,Coffee,2.0,2.0,4.000000,Digital Wallet,In-store,6/11/2023
5,TXN,2602893,Smoothie,5.0,4.0,20.000000,Credit Card,Unknown,3/31/2023
6,TXN,4433211,Unknown,3.0,3.0,9.000000,Unknown,Takeaway,10/6/2023
7,TXN,6699534,Sandwich,4.0,4.0,16.000000,Cash,Unknown,10/28/2023
8,TXN,4717867,Unknown,5.0,3.0,15.000000,Unknown,Takeaway,7/28/2023
9,TXN,2064365,Sandwich,5.0,4.0,20.000000,Unknown,In-store,12/31/2023
10,TXN,2548360,Salad,5.0,5.0,25.000000,Cash,Takeaway,11/7/2023
11,TXN,3051279,Sandwich,2.0,4.0,8.000000,Credit Card,Takeaway,1/1/2023
12,TXN,7619095,Sandwich,2.0,4.0,8.000000,Cash,In-store,5/3/2023
13,TXN,9437049,Cookie,5.0,1.0,5.000000,Unknown,Takeaway,6/1/2023
14,TXN,8915701,Unknown,2.0,1.5,3.000000,Unknown,In-store,3/21/2023
15,TXN,2847255,Salad,3.0,5.0,15.000000,Credit Card,In-store,11/15/2023
16,TXN,3765707,Sandwich,1.0,4.0,4.000000,Unknown,Unknown,6/10/2023
17,TXN,6769710,Juice,2.0,3.0,6.000000,Cash,In-store,2/24/2023
18,TXN,8876618,Cake,5.0,3.0,15.000000,Cash,Unknown,3/25/2023
19,TXN,3709394,Juice,4.0,3.0,12.000000,Cash,Takeaway,1/15/2023

In [21]:
df.shape

(10000, 9)

In [22]:
df.columns.tolist()

['TXN',
 'Transaction number ',
 'Item ',
 'Quantity_Avg',
 'Price_per_unit_Avg',
 'Total_spent_Avg',
 'Payment Method',
 'Location',
 'Transaction Date']

In [23]:
df.columns = df.columns.str.strip()
df.columns.tolist()

['TXN',
 'Transaction number',
 'Item',
 'Quantity_Avg',
 'Price_per_unit_Avg',
 'Total_spent_Avg',
 'Payment Method',
 'Location',
 'Transaction Date']

In [24]:
df.rename(columns={
    'Transaction number': 'Transaction_Number',
    'Item': 'Item',
    'Quantity_Avg': 'Quantity',
    'Price_per_unit_Avg': 'Price_Per_Unit',
    'Total_spent_Avg': 'Total_Spent',
    'Payment Method': 'Payment_Method',
    'Transaction Date': 'Transaction_Date'
}, inplace=True)

df.columns.tolist()

['TXN',
 'Transaction_Number',
 'Item',
 'Quantity',
 'Price_Per_Unit',
 'Total_Spent',
 'Payment_Method',
 'Location',
 'Transaction_Date']

In [25]:
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])
df['Transaction_Date'].dtype

dtype('<M8[ns]')

In [26]:
df['Month'] = df['Transaction_Date'].dt.month_name()
df['Year'] = df['Transaction_Date'].dt.year
df.head(10)

,TXN,Transaction_Number,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date,Month,Year
0,TXN,1961373,Coffee,2.0,2.0,4.000000,Credit Card,Takeaway,2023-09-08,September,2023
1,TXN,4977031,Cake,4.0,3.0,12.000000,Cash,In-store,2023-05-16,May,2023
2,TXN,4271903,Cookie,4.0,1.0,8.924352,Credit Card,In-store,2023-07-19,July,2023
3,TXN,7034554,Salad,2.0,5.0,10.000000,Unknown,Unknown,2023-04-27,April,2023
4,TXN,3160411,Coffee,2.0,2.0,4.000000,Digital Wallet,In-store,2023-06-11,June,2023
5,TXN,2602893,Smoothie,5.0,4.0,20.000000,Credit Card,Unknown,2023-03-31,March,2023
6,TXN,4433211,Unknown,3.0,3.0,9.000000,Unknown,Takeaway,2023-10-06,October,2023
7,TXN,6699534,Sandwich,4.0,4.0,16.000000,Cash,Unknown,2023-10-28,October,2023
8,TXN,4717867,Unknown,5.0,3.0,15.000000,Unknown,Takeaway,2023-07-28,July,2023
9,TXN,2064365,Sandwich,5.0,4.0,20.000000,Unknown,In-store,2023-12-31,December,2023

In [27]:
df.dtypes

TXN                           object
Transaction_Number             int64
Item                          object
Quantity                     float64
Price_Per_Unit               float64
Total_Spent                  float64
Payment_Method                object
Location                      object
Transaction_Date      datetime64[ns]
Month                         object
Year                           int32
dtype: object

In [28]:
df.describe()

,Transaction_Number,Quantity,Price_Per_Unit,Total_Spent,Transaction_Date,Year
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000,10000.0
mean,5.474016e+06,3.028463,2.949984,8.924352,2023-06-23 14:07:35.040000,2023.0
min,1.000555e+06,1.000000,1.000000,1.000000,2023-01-01 00:00:00,2023.0
25%,3.219544e+06,2.000000,2.000000,4.000000,2023-03-19 00:00:00,2023.0
50%,5.453098e+06,3.000000,3.000000,8.000000,2023-06-24 00:00:00,2023.0
75%,7.730994e+06,4.000000,4.000000,12.000000,2023-09-27 00:00:00,2023.0
max,9.999124e+06,5.000000,5.000000,25.000000,2023-12-31 00:00:00,2023.0
std,2.596022e+06,1.384601,1.243910,5.857113,NaN,0.0

In [29]:
total_revenue = df['Total_Spent'].sum()
print(f"Total Revenue: ${total_revenue:,.2f}")

Total Revenue: $89,243.52

In [30]:
best_selling = df.groupby('Item')['Quantity'].sum().sort_values(ascending=False)
print(best_selling)

Item
Coffee      3552.736267
Juice       3515.337780
Salad       3470.508560
Cake        3468.309316
Sandwich    3429.736267
Smoothie    3354.252389
Tea         3320.565487
Cookie      3250.508560
Unknown     2922.679340
Name: Quantity, dtype: float64

In [31]:
revenue_by_item = df.groupby('Item')['Total_Spent'].sum().sort_values(ascending=False)
print(revenue_by_item)

Item
Salad       17069.066330
Sandwich    13545.007265
Smoothie    13198.553380
Juice       10483.763740
Cake        10388.141977
Unknown      8586.217625
Coffee       7230.217625
Tea          5163.868920
Cookie       3578.688092
Name: Total_Spent, dtype: float64

In [32]:
revenue_by_payment = df.groupby('Payment_Method')['Total_Spent'].sum().sort_values(ascending=False)
print(revenue_by_payment)

Payment_Method
Unknown           27777.639924
Credit Card       20509.283954
Digital Wallet    20506.132659
Cash              20450.468414
Name: Total_Spent, dtype: float64

In [33]:
revenue_by_location = df.groupby('Location')['Total_Spent'].sum().sort_values(ascending=False)
print(revenue_by_location)

Location
Unknown     35448.567909
In-store    27226.804169
Takeaway    26568.152874
Name: Total_Spent, dtype: float64

In [34]:
revenue_by_month = df.groupby('Month')['Total_Spent'].sum().sort_values(ascending=False)
print(revenue_by_month)

Month
January      11459.477732
October       7370.701042
June          7357.079280
March         7241.444567
April         7185.641977
August        7136.033165
December      7131.201042
May           7004.201042
July          6948.822805
November      6925.171510
September     6867.398452
February      6616.352337
Name: Total_Spent, dtype: float64

In [35]:
df.to_csv("CAFE_SALES_FINAL.csv", index=False)
print("File saved successfully!")

File saved successfully!

In [36]:
verify = pd.read_csv("CAFE_SALES_FINAL.csv")
print(verify.shape)
verify.head()

(10000, 11)

,TXN,Transaction_Number,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date,Month,Year
0,TXN,1961373,Coffee,2.0,2.0,4.000000,Credit Card,Takeaway,2023-09-08,September,2023
1,TXN,4977031,Cake,4.0,3.0,12.000000,Cash,In-store,2023-05-16,May,2023
2,TXN,4271903,Cookie,4.0,1.0,8.924352,Credit Card,In-store,2023-07-19,July,2023
3,TXN,7034554,Salad,2.0,5.0,10.000000,Unknown,Unknown,2023-04-27,April,2023
4,TXN,3160411,Coffee,2.0,2.0,4.000000,Digital Wallet,In-store,2023-06-11,June,2023

In [37]:
verify = pd.read_csv("CAFE_SALES_FINAL.csv")
print("Columns in file:")
print(verify.columns.tolist())
print()
print("Shape:", verify.shape)
print()
verify.head()

Columns in file:
['TXN', 'Transaction_Number', 'Item', 'Quantity', 'Price_Per_Unit', 'Total_Spent', 'Payment_Method', 'Location', 'Transaction_Date', 'Month', 'Year']

Shape: (10000, 11)

,TXN,Transaction_Number,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date,Month,Year
0,TXN,1961373,Coffee,2.0,2.0,4.000000,Credit Card,Takeaway,2023-09-08,September,2023
1,TXN,4977031,Cake,4.0,3.0,12.000000,Cash,In-store,2023-05-16,May,2023
2,TXN,4271903,Cookie,4.0,1.0,8.924352,Credit Card,In-store,2023-07-19,July,2023
3,TXN,7034554,Salad,2.0,5.0,10.000000,Unknown,Unknown,2023-04-27,April,2023
4,TXN,3160411,Coffee,2.0,2.0,4.000000,Digital Wallet,In-store,2023-06-11,June,2023